/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import filter.Evaluator;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import metrics.MetricMethod;
import metrics.MetricPackage;
import metrics.MetricType;

/**
 *
 * @author bruno
 */
public class CreateDetectionStrategyForm extends javax.swing.JFrame {

    /**
     * Creates new form CreateDetectionStrategy
     */
    public CreateDetectionStrategyForm() {
        initComponents();
        initPanels();
        loadVariablesToValue();
    }

    public CreateDetectionStrategyForm(FilterSystemForm frame) {
        this.frame = frame;
        initComponents();
        initPanels();
        loadVariablesToValue();
    }

    public CreateDetectionStrategyForm(String name, String granularity, String expression, FilterSystemForm frame) {
        initComponents();
        initPanels(granularity);
        loadVariablesToValue();
        this.jTextFieldNameDetectionStrategy.setText(name);
        this.jTextAreaDetectionStrategy.setText(expression);
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMethod = new javax.swing.JPanel();
        jButtonMetricMLOC = new javax.swing.JButton();
        jButtonMetricNBD = new javax.swing.JButton();
        jButtonMetricPAR = new javax.swing.JButton();
        jButtonMetricVG = new javax.swing.JButton();
        jLabelOptionDetectionStrategy = new javax.swing.JLabel();
        jRadioButtonMethod = new javax.swing.JRadioButton();
        jRadioButtonPackage = new javax.swing.JRadioButton();
        jRadioButtonType = new javax.swing.JRadioButton();
        jPanelPackage = new javax.swing.JPanel();
        jButtonCA = new javax.swing.JButton();
        jButtonCE = new javax.swing.JButton();
        jButtonNOC = new javax.swing.JButton();
        jButtonNOI = new javax.swing.JButton();
        jButtonRMA = new javax.swing.JButton();
        jButtonRMD = new javax.swing.JButton();
        jButtonRMI = new javax.swing.JButton();
        jPanelType = new javax.swing.JPanel();
        jButtonDIT = new javax.swing.JButton();
        jButtonLCOM = new javax.swing.JButton();
        jButtonNOF = new javax.swing.JButton();
        jButtonNOM = new javax.swing.JButton();
        jButtonNORM = new javax.swing.JButton();
        jButtonNSC = new javax.swing.JButton();
        jButtonNSF = new javax.swing.JButton();
        jButtonNSM = new javax.swing.JButton();
        jButtonSIX = new javax.swing.JButton();
        jButtonWMC = new javax.swing.JButton();
        jPanelOperators = new javax.swing.JPanel();
        jButtonAND = new javax.swing.JButton();
        jButtonOR = new javax.swing.JButton();
        jButtonOpenParenthesis = new javax.swing.JButton();
        jButtonCloseParenthesis = new javax.swing.JButton();
        jButtonValue = new javax.swing.JButton();
        jButtonSmaller = new javax.swing.JButton();
        jButtonLarger = new javax.swing.JButton();
        jButtonEquals = new javax.swing.JButton();
        jButtonSmallerEquals = new javax.swing.JButton();
        jButtonLargerEquals = new javax.swing.JButton();
        jPanelDetectionStrategy = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDetectionStrategy = new javax.swing.JTextArea();
        jButtonClean = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        jLabelNameDetectionStrategy = new javax.swing.JLabel();
        jTextFieldNameDetectionStrategy = new javax.swing.JTextField();
        jButtonBackspace = new javax.swing.JButton();

        setTitle("FindSmells");
        setResizable(false);

        jPanelMain.setBorder(javax.swing.BorderFactory.createTitledBorder("Detection Strategy"));

        jPanelMethod.setBorder(javax.swing.BorderFactory.createTitledBorder("Metrics of Method"));

        jButtonMetricMLOC.setText("MLOC");
        jButtonMetricMLOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMetricMLOCActionPerformed(evt);
            }
        });

        jButtonMetricNBD.setText("NBD");
        jButtonMetricNBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMetricNBDActionPerformed(evt);
            }
        });

        jButtonMetricPAR.setText("PAR");
        jButtonMetricPAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMetricPARActionPerformed(evt);
            }
        });

        jButtonMetricVG.setText("VG");
        jButtonMetricVG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMetricVGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMethodLayout = new javax.swing.GroupLayout(jPanelMethod);
        jPanelMethod.setLayout(jPanelMethodLayout);
        jPanelMethodLayout.setHorizontalGroup(
            jPanelMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMethodLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMetricNBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMetricMLOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMetricPAR, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jButtonMetricVG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelMethodLayout.setVerticalGroup(
            jPanelMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMethodLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMetricMLOC)
                    .addComponent(jButtonMetricPAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMethodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMetricNBD)
                    .addComponent(jButtonMetricVG))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelOptionDetectionStrategy.setText("Granularity of detection strategy: ");

        jRadioButtonMethod.setText("Method");
        jRadioButtonMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMethodActionPerformed(evt);
            }
        });

        jRadioButtonPackage.setText("Package");
        jRadioButtonPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPackageActionPerformed(evt);
            }
        });

        jRadioButtonType.setText("Class");
        jRadioButtonType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTypeActionPerformed(evt);
            }
        });

        jPanelPackage.setBorder(javax.swing.BorderFactory.createTitledBorder("Metrics of Package"));

        jButtonCA.setText("CA");
        jButtonCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCAActionPerformed(evt);
            }
        });

        jButtonCE.setText("CE");
        jButtonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCEActionPerformed(evt);
            }
        });

        jButtonNOC.setText("NOC");
        jButtonNOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNOCActionPerformed(evt);
            }
        });

        jButtonNOI.setText("NOI");
        jButtonNOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNOIActionPerformed(evt);
            }
        });

        jButtonRMA.setText("RMA");
        jButtonRMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRMAActionPerformed(evt);
            }
        });

        jButtonRMD.setText("RMD");
        jButtonRMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRMDActionPerformed(evt);
            }
        });

        jButtonRMI.setText("RMI");
        jButtonRMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRMIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPackageLayout = new javax.swing.GroupLayout(jPanelPackage);
        jPanelPackage.setLayout(jPanelPackageLayout);
        jPanelPackageLayout.setHorizontalGroup(
            jPanelPackageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPackageLayout.createSequentialGroup()
                .addGroup(jPanelPackageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNOI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPackageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRMI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelPackageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPackageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRMD))
                    .addGroup(jPanelPackageLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonNOC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelPackageLayout.setVerticalGroup(
            jPanelPackageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPackageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPackageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCA)
                    .addComponent(jButtonCE)
                    .addComponent(jButtonNOC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPackageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNOI)
                    .addComponent(jButtonRMA)
                    .addComponent(jButtonRMD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRMI)
                .addContainerGap())
        );

        jPanelType.setBorder(javax.swing.BorderFactory.createTitledBorder("Metrics of Class"));

        jButtonDIT.setText("DIT");
        jButtonDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDITActionPerformed(evt);
            }
        });

        jButtonLCOM.setText("LCOM");
        jButtonLCOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLCOMActionPerformed(evt);
            }
        });

        jButtonNOF.setText("NOF");
        jButtonNOF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNOFActionPerformed(evt);
            }
        });

        jButtonNOM.setText("NOM");
        jButtonNOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNOMActionPerformed(evt);
            }
        });

        jButtonNORM.setText("NORM");
        jButtonNORM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNORMActionPerformed(evt);
            }
        });

        jButtonNSC.setText("NSC");
        jButtonNSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNSCActionPerformed(evt);
            }
        });

        jButtonNSF.setText("NSF");
        jButtonNSF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNSFActionPerformed(evt);
            }
        });

        jButtonNSM.setText("NSM");
        jButtonNSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNSMActionPerformed(evt);
            }
        });

        jButtonSIX.setText("SIX");
        jButtonSIX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSIXActionPerformed(evt);
            }
        });

        jButtonWMC.setText("WMC");
        jButtonWMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWMCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTypeLayout = new javax.swing.GroupLayout(jPanelType);
        jPanelType.setLayout(jPanelTypeLayout);
        jPanelTypeLayout.setHorizontalGroup(
            jPanelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTypeLayout.createSequentialGroup()
                        .addComponent(jButtonDIT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLCOM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNOF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNOM))
                    .addGroup(jPanelTypeLayout.createSequentialGroup()
                        .addComponent(jButtonNORM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNSC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNSF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNSM))
                    .addGroup(jPanelTypeLayout.createSequentialGroup()
                        .addComponent(jButtonSIX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonWMC)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTypeLayout.setVerticalGroup(
            jPanelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDIT)
                    .addComponent(jButtonLCOM)
                    .addComponent(jButtonNOF)
                    .addComponent(jButtonNOM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNORM)
                    .addComponent(jButtonNSC)
                    .addComponent(jButtonNSF)
                    .addComponent(jButtonNSM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSIX)
                    .addComponent(jButtonWMC))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelOperators.setBorder(javax.swing.BorderFactory.createTitledBorder("Operators"));

        jButtonAND.setText("AND");
        jButtonAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonANDActionPerformed(evt);
            }
        });

        jButtonOR.setText("OR");
        jButtonOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonORActionPerformed(evt);
            }
        });

        jButtonOpenParenthesis.setText("(");
        jButtonOpenParenthesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenParenthesisActionPerformed(evt);
            }
        });

        jButtonCloseParenthesis.setText(")");
        jButtonCloseParenthesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseParenthesisActionPerformed(evt);
            }
        });

        jButtonValue.setText("VALUE");
        jButtonValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValueActionPerformed(evt);
            }
        });

        jButtonSmaller.setText("<");
        jButtonSmaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSmallerActionPerformed(evt);
            }
        });

        jButtonLarger.setText(">");
        jButtonLarger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLargerActionPerformed(evt);
            }
        });

        jButtonEquals.setText("=");
        jButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualsActionPerformed(evt);
            }
        });

        jButtonSmallerEquals.setText("<=");
        jButtonSmallerEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSmallerEqualsActionPerformed(evt);
            }
        });

        jButtonLargerEquals.setText(">=");
        jButtonLargerEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLargerEqualsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOperatorsLayout = new javax.swing.GroupLayout(jPanelOperators);
        jPanelOperators.setLayout(jPanelOperatorsLayout);
        jPanelOperatorsLayout.setHorizontalGroup(
            jPanelOperatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOperatorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAND)
                .addGap(18, 18, 18)
                .addComponent(jButtonOR)
                .addGap(18, 18, 18)
                .addComponent(jButtonOpenParenthesis)
                .addGap(18, 18, 18)
                .addComponent(jButtonCloseParenthesis)
                .addGap(18, 18, 18)
                .addComponent(jButtonValue)
                .addGap(18, 18, 18)
                .addComponent(jButtonSmaller)
                .addGap(18, 18, 18)
                .addComponent(jButtonLarger)
                .addGap(18, 18, 18)
                .addComponent(jButtonEquals)
                .addGap(18, 18, 18)
                .addComponent(jButtonSmallerEquals)
                .addGap(18, 18, 18)
                .addComponent(jButtonLargerEquals)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOperatorsLayout.setVerticalGroup(
            jPanelOperatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOperatorsLayout.createSequentialGroup()
                .addGroup(jPanelOperatorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAND)
                    .addComponent(jButtonOR)
                    .addComponent(jButtonOpenParenthesis)
                    .addComponent(jButtonCloseParenthesis)
                    .addComponent(jButtonValue)
                    .addComponent(jButtonSmaller)
                    .addComponent(jButtonLarger)
                    .addComponent(jButtonEquals)
                    .addComponent(jButtonSmallerEquals)
                    .addComponent(jButtonLargerEquals))
                .addGap(0, 63, Short.MAX_VALUE))
        );

        jPanelDetectionStrategy.setBorder(javax.swing.BorderFactory.createTitledBorder("Expression"));

        jTextAreaDetectionStrategy.setEditable(false);
        jTextAreaDetectionStrategy.setColumns(20);
        jTextAreaDetectionStrategy.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDetectionStrategy);

        javax.swing.GroupLayout jPanelDetectionStrategyLayout = new javax.swing.GroupLayout(jPanelDetectionStrategy);
        jPanelDetectionStrategy.setLayout(jPanelDetectionStrategyLayout);
        jPanelDetectionStrategyLayout.setHorizontalGroup(
            jPanelDetectionStrategyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetectionStrategyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelDetectionStrategyLayout.setVerticalGroup(
            jPanelDetectionStrategyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetectionStrategyLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jButtonClean.setText("Clean");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jLabelNameDetectionStrategy.setText("Name of Detection Strategy:");

        jButtonBackspace.setText("Backspace");
        jButtonBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackspaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jPanelOperators, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jPanelMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelDetectionStrategy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addComponent(jButtonClean)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBackspace)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRegister)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabelOptionDetectionStrategy)
                        .addGap(73, 73, 73)
                        .addComponent(jRadioButtonMethod)
                        .addGap(94, 94, 94)
                        .addComponent(jRadioButtonPackage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonType)
                        .addGap(65, 65, 65))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabelNameDetectionStrategy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNameDetectionStrategy)
                        .addContainerGap())))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameDetectionStrategy)
                    .addComponent(jTextFieldNameDetectionStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOptionDetectionStrategy)
                    .addComponent(jRadioButtonMethod)
                    .addComponent(jRadioButtonType)
                    .addComponent(jRadioButtonPackage))
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelMethod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPackage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanelType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOperators, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDetectionStrategy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonClean)
                        .addComponent(jButtonBackspace))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addComponent(jButtonRegister)
                        .addContainerGap())))
        );

        jPanelMethod.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMethodActionPerformed
        this.jRadioButtonPackage.setSelected(false);
        this.jRadioButtonType.setSelected(false);
        this.jTextAreaDetectionStrategy.setText("");
        enablePanelMethods(true);
        enablePanelPackage(false);
        enablePanelType(false);
        this.granularity = this.jRadioButtonMethod.getText();
    }//GEN-LAST:event_jRadioButtonMethodActionPerformed

    private void jRadioButtonPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPackageActionPerformed
        this.jRadioButtonMethod.setSelected(false);
        this.jRadioButtonType.setSelected(false);
        this.jTextAreaDetectionStrategy.setText("");
        enablePanelMethods(false);
        enablePanelPackage(true);
        enablePanelType(false);
        this.granularity = this.jRadioButtonPackage.getText();
    }//GEN-LAST:event_jRadioButtonPackageActionPerformed

    private void jRadioButtonTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTypeActionPerformed
        this.jRadioButtonPackage.setSelected(false);
        this.jRadioButtonMethod.setSelected(false);
        this.jTextAreaDetectionStrategy.setText("");
        enablePanelMethods(false);
        enablePanelPackage(false);
        enablePanelType(true);
        this.granularity = this.jRadioButtonType.getText();
    }//GEN-LAST:event_jRadioButtonTypeActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
        this.jTextAreaDetectionStrategy.setText("");
    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jButtonMetricMLOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMetricMLOCActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "mloc";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonMetricMLOCActionPerformed

    private void jButtonMetricPARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMetricPARActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "par";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonMetricPARActionPerformed

    private void jButtonMetricNBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMetricNBDActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "nbd";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonMetricNBDActionPerformed

    private void jButtonMetricVGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMetricVGActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "vg";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonMetricVGActionPerformed

    private void jButtonCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCAActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "ca";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonCAActionPerformed

    private void jButtonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCEActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "ce";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonCEActionPerformed

    private void jButtonNOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNOCActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "noc";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonNOCActionPerformed

    private void jButtonNOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNOIActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "noi";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonNOIActionPerformed

    private void jButtonRMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRMAActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "rma";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonRMAActionPerformed

    private void jButtonRMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRMDActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "rmd";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonRMDActionPerformed

    private void jButtonRMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRMIActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "rmi";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonRMIActionPerformed

    private void jButtonDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDITActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "dit";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonDITActionPerformed

    private void jButtonLCOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLCOMActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "lcom";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonLCOMActionPerformed

    private void jButtonNOFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNOFActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "nof";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonNOFActionPerformed

    private void jButtonNOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNOMActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "nom";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonNOMActionPerformed

    private void jButtonNORMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNORMActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "norm";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonNORMActionPerformed

    private void jButtonNSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNSCActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "nsc";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonNSCActionPerformed

    private void jButtonNSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNSFActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "nsf";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonNSFActionPerformed

    private void jButtonNSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNSMActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "nsm";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonNSMActionPerformed

    private void jButtonSIXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSIXActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "six";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonSIXActionPerformed

    private void jButtonWMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWMCActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "wmc";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonWMCActionPerformed

    private void jButtonANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonANDActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "AND ";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonANDActionPerformed

    private void jButtonORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonORActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "OR ";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonORActionPerformed

    private void jButtonOpenParenthesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenParenthesisActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "( ";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonOpenParenthesisActionPerformed

    private void jButtonCloseParenthesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseParenthesisActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += ") ";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonCloseParenthesisActionPerformed

    private void jButtonValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValueActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "VALUE ";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonValueActionPerformed

    private void jButtonSmallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSmallerActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "<";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonSmallerActionPerformed

    private void jButtonLargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLargerActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += ">";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonLargerActionPerformed

    private void jButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualsActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "=";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonEqualsActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        if (!this.jTextAreaDetectionStrategy.getText().isEmpty() && !this.jTextFieldNameDetectionStrategy.getText().isEmpty()) {
            String expression = this.jTextAreaDetectionStrategy.getText();
            Evaluator evaluator = new Evaluator();
            if (evaluator.evaluate(expression)) {
                PutThresholdForm putThreshold = new PutThresholdForm(this.jTextFieldNameDetectionStrategy.getText(), this.granularity, expression, this.frame);
                putThreshold.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect expression! Check for errors in the expression.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Make sure that the fields \"Name of Detection Strategy\" and \"Expression\" are completed!", "Attention", JOptionPane.WARNING_MESSAGE, null);
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonSmallerEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSmallerEqualsActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += "<=";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonSmallerEqualsActionPerformed

    private void jButtonLargerEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLargerEqualsActionPerformed
        String detectionStrategy = this.jTextAreaDetectionStrategy.getText();
        detectionStrategy += ">=";
        this.jTextAreaDetectionStrategy.setText(detectionStrategy);
    }//GEN-LAST:event_jButtonLargerEqualsActionPerformed

    private void jButtonBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackspaceActionPerformed
        if (!jTextAreaDetectionStrategy.getText().isEmpty()) {
            String[] split = this.jTextAreaDetectionStrategy.getText().split(" ");
            String strategy = "";
            for (int i = 0; i < (split.length - 1); i++) {
                strategy += split[i] + " ";
            }
            this.jTextAreaDetectionStrategy.setText(strategy);
        }
    }//GEN-LAST:event_jButtonBackspaceActionPerformed

    private void initPanels() {
        enablePanelType(true);
        enablePanelMethods(false);
        enablePanelPackage(false);
        this.jRadioButtonType.setSelected(true);
        this.granularity = this.jRadioButtonType.getText();
    }

    private void initPanels(String granularity) {
        if (granularity.equals("Method")) {
            enablePanelMethods(true);
            enablePanelPackage(false);
            enablePanelType(false);
            this.jRadioButtonMethod.setSelected(true);
        } else if (granularity.equals("Package")) {
            enablePanelMethods(false);
            enablePanelPackage(true);
            enablePanelType(false);
            this.jRadioButtonPackage.setSelected(true);
        } else if (granularity.equals("Class")) {
            enablePanelMethods(false);
            enablePanelPackage(false);
            enablePanelType(true);
            this.jRadioButtonType.setSelected(true);
        }
        this.granularity = granularity;
    }

    private void enablePanelMethods(boolean status) {
        this.jButtonMetricMLOC.setEnabled(status);
        this.jButtonMetricPAR.setEnabled(status);
        this.jButtonMetricNBD.setEnabled(status);
        this.jButtonMetricVG.setEnabled(status);
        this.jPanelMethod.setEnabled(status);
    }

    private void enablePanelPackage(boolean status) {
        this.jButtonCA.setEnabled(status);
        this.jButtonCE.setEnabled(status);
        this.jButtonNOC.setEnabled(status);
        this.jButtonNOI.setEnabled(status);
        this.jButtonRMA.setEnabled(status);
        this.jButtonRMD.setEnabled(status);
        this.jButtonRMI.setEnabled(status);
        this.jPanelPackage.setEnabled(status);
    }

    private void enablePanelType(boolean status) {
        this.jButtonDIT.setEnabled(status);
        this.jButtonLCOM.setEnabled(status);
        this.jButtonNOF.setEnabled(status);
        this.jButtonNOM.setEnabled(status);
        this.jButtonNORM.setEnabled(status);
        this.jButtonNSC.setEnabled(status);
        this.jButtonNSF.setEnabled(status);
        this.jButtonNSM.setEnabled(status);
        this.jButtonSIX.setEnabled(status);
        this.jButtonWMC.setEnabled(status);
        this.jPanelType.setEnabled(status);
    }

    private void loadVariablesToValue() {
        this.variables = new HashMap<>();
        for (MetricMethod metric : MetricMethod.values()) {
            this.variables.put(metric.toString().toLowerCase(), "VALUE");
        }
        for (MetricPackage metric : MetricPackage.values()) {
            this.variables.put(metric.toString().toLowerCase(), "VALUE");
        }
        for (MetricType metric : MetricType.values()) {
            this.variables.put(metric.toString().toLowerCase(), "VALUE");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAND;
    private javax.swing.JButton jButtonBackspace;
    private javax.swing.JButton jButtonCA;
    private javax.swing.JButton jButtonCE;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JButton jButtonCloseParenthesis;
    private javax.swing.JButton jButtonDIT;
    private javax.swing.JButton jButtonEquals;
    private javax.swing.JButton jButtonLCOM;
    private javax.swing.JButton jButtonLarger;
    private javax.swing.JButton jButtonLargerEquals;
    private javax.swing.JButton jButtonMetricMLOC;
    private javax.swing.JButton jButtonMetricNBD;
    private javax.swing.JButton jButtonMetricPAR;
    private javax.swing.JButton jButtonMetricVG;
    private javax.swing.JButton jButtonNOC;
    private javax.swing.JButton jButtonNOF;
    private javax.swing.JButton jButtonNOI;
    private javax.swing.JButton jButtonNOM;
    private javax.swing.JButton jButtonNORM;
    private javax.swing.JButton jButtonNSC;
    private javax.swing.JButton jButtonNSF;
    private javax.swing.JButton jButtonNSM;
    private javax.swing.JButton jButtonOR;
    private javax.swing.JButton jButtonOpenParenthesis;
    private javax.swing.JButton jButtonRMA;
    private javax.swing.JButton jButtonRMD;
    private javax.swing.JButton jButtonRMI;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonSIX;
    private javax.swing.JButton jButtonSmaller;
    private javax.swing.JButton jButtonSmallerEquals;
    private javax.swing.JButton jButtonValue;
    private javax.swing.JButton jButtonWMC;
    private javax.swing.JLabel jLabelNameDetectionStrategy;
    private javax.swing.JLabel jLabelOptionDetectionStrategy;
    private javax.swing.JPanel jPanelDetectionStrategy;
    private final javax.swing.JPanel jPanelMain = new javax.swing.JPanel();
    private javax.swing.JPanel jPanelMethod;
    private javax.swing.JPanel jPanelOperators;
    private javax.swing.JPanel jPanelPackage;
    private javax.swing.JPanel jPanelType;
    private javax.swing.JRadioButton jRadioButtonMethod;
    private javax.swing.JRadioButton jRadioButtonPackage;
    private javax.swing.JRadioButton jRadioButtonType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDetectionStrategy;
    private javax.swing.JTextField jTextFieldNameDetectionStrategy;
    // End of variables declaration//GEN-END:variables
    private Map<String, String> variables;
    private String granularity;
    private FilterSystemForm frame;
}
